### ISSUE TITLE
Add Don’t Require FormAPI

### ISSUE THREAD

**Issue by xXNiceYT** [QuiverlyRivalry/ShopUI#1]
Yo hi

**Comment by nasiridrishi** [comment]
@QuiverlyRivalry awesome job by the way haha:))

**Comment by nasiridrishi** [comment]
Would be awesome if you added config better lol!! Life saving for you:))

**Comment by pranavbhuv** [comment]
It needs formsapi
@optimusprime338 im still learning configs but maybw
