### ISSUE TITLE
menu blocks doesnt work

### ISSUE THREAD

**Issue by llronaldoll** [QuiverlyRivalry/ShopUI#10]
when clicking on the blocks menu, nothing happens!

**Comment by pranavbhuv** [comment]
When I come home I’ll take a look @DaPigGuy

**Comment by DaPigGuy** [comment]
I durped a little & forgot to add the price for Stone Slab & Bookshelf. I opened another PR (#11) to solve this. However, if you had a config prior to the commit, you'll have to either delete your config or go to lines 58 & 59 and replace those lines with
```
    - "44:0:64:Stone Slab:25000:0:textures/items/stone_slab"
    - "47:0:64:Bookshelf:25000:0:textures/items/bookshelf"
```
