### ISSUE TITLE
stuff

### ISSUE THREAD

**Issue by ShotDead7297** [QuiverlyRivalry/ShopUI#17]
this is so trash it doesn't work

**Comment by iZeaoGamer** [comment]
There's no need to give insults of this plugin. If it "doesn't work" as you say, then why not be more specific on what doesn't work? Like, saying "it doesn't work" doesn't exactly proven nor help them fix the issue you're having. So next time, don't say something's trash without a valid reason. Thanks.

**Comment by ShotDead7297** [comment]
ok sorry

**Comment by ShotDead7297** [comment]
it looks like u fix plugins humm well u should fix that boss plugin it dont work lol
